// JavaScript Document
      var openMapIcon = {
          url: 'img/web_design/map-open-icon.png',
          size: new google.maps.Size(24, 24),
          origin: new google.maps.Point(0,0),
          anchor: new google.maps.Point(5, 24)
        };
		
      var seasonalMapIcon = Object.create(openMapIcon);
        seasonalMapIcon.url = 'img/web_design/map-open-icon.png';
        seasonalMapIcon.anchor = new google.maps.Point(-8, 36);
        		
      var closedMapIcon = Object.create(openMapIcon);
        closedMapIcon.url = 'img/web_design/map-closed-icon.png';
        closedMapIcon.anchor = new google.maps.Point(21, 24);

 var center = null;
 var map = null;
 var currentPopup;
 var bounds = new google.maps.LatLngBounds();
 
 function addMarkerOpen(lat, lng, html) {
	 var pt = new google.maps.LatLng(lat, lng);
	 bounds.extend(pt);
	var marker = new google.maps.Marker({
			 position: pt,
			 icon: openMapIcon,
			 map: map
		 });
		 
	var popup = new google.maps.InfoWindow({
		 content: html,
		 maxWidth: 250
	 });
	
	google.maps.event.addListener(marker, "click", function() {
		 if (currentPopup != null) {
			 currentPopup.close();
			 currentPopup = null;
		 }
		 popup.open(map, marker);
		 currentPopup = popup;
	});
	 google.maps.event.addListener(popup, "closeclick", function() {
	 currentPopup = null;
	 });
 }
 
 function addMarkerSeasonal(lat, lng, html) {
	 var pt = new google.maps.LatLng(lat, lng);
	 bounds.extend(pt);
	var marker = new google.maps.Marker({
			 position: pt,
			 icon: seasonalMapIcon,
			 map: map
		 });
	var popup = new google.maps.InfoWindow({
		 content: html,
		 maxWidth: 250
	 });
	google.maps.event.addListener(marker, "click", function() {
		 if (currentPopup != null) {
			 currentPopup.close();
			 currentPopup = null;
		 }
		 popup.open(map, marker);
		 currentPopup = popup;
	});
	 google.maps.event.addListener(popup, "closeclick", function() {
	 currentPopup = null;
	 });
 }

 function addMarkerClosed (lat, lng, html) {
     var pt = new google.maps.LatLng(lat, lng);
     bounds.extend(pt);
    var marker = new google.maps.Marker({
         position: pt,
         icon: closedMapIcon,
         map: map
       });
     var popup = new google.maps.InfoWindow({
       content: html,
       maxWidth: 250
     });
    google.maps.event.addListener(marker, "click", function() {
       if (currentPopup != null) {
         currentPopup.close();
         currentPopup = null;
       }
       popup.open(map, marker);
       currentPopup = popup;
    });
     google.maps.event.addListener(popup, "closeclick", function() {
     currentPopup = null;
     });
   }

 function initialize() {
	 map = new google.maps.Map(document.getElementById("google-map"), {
		 center: new google.maps.LatLng(37.7945928242851, -121.81365966796875),
		 zoom: 8,
		 mapTypeId: google.maps.MapTypeId.ROADMAP,
		 mapTypeControl: false,
		 mapTypeControlOptions: {
			style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR
		 },
		 navigationControl: true,
		 navigationControlOptions: {
			style: google.maps.NavigationControlStyle.SMALL
		}
	});

	// extracting and looping through data
		 
 //<![CDATA[

addMarkerClosed(37.955246, -122.332397,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">San Pablo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 18 to October 26</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.679829, -121.768784,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Livermore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 16 to October 17</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.003571, -121.841812,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Antioch at Somersville Towne Center</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 12 to October 27</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.332016, -121.913429,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Hanchett Avenue</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11 to October 26</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.788280, -122.420189,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Fern Alley</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11 to October 26</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.940849, -121.935921,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Clayton</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11 to October 26</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.926376, -122.384911,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Point Richmond</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 9 to September 26</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.936546, -122.356728,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Richmond Main Street</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 8 to October 30</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.345058, -121.876915,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">East Santa Clara Street</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 8 to October 23</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.658943, -122.439545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Kaiser South San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 7 to October 15</dd><dt class="gmapInfoWindowAPIv3"> Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.543766, -122.309883,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">25th Avenue in San Mateo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 7 to October 15</dd><dt class="gmapInfoWindowAPIv3"> Tuesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 7:30 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.634850, -122.419434,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">San Bruno</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 5 to November 24</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.032188, -121.883759,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Pittsburg</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4 to December 14</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.654930, -122.426704,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">South San Francisco</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4 to October 26</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.678699, -122.126907,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">San Lorenzo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4 to October 19</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.944740, -122.061615,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Pleasant Hill</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4 to November 16</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.356686, -121.989304,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Vacaville</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4 to October 12</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.335411, -121.893127,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">San Jose Downtown</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 3 to November 22</dd><dt class="gmapInfoWindowAPIv3"> Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.951717, -121.776802,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Kaiser Permanente Antioch</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 2 to October 31</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.249386, -122.041908,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Fairfield</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 2 to October 3</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">3:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.488914, -122.221664,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Kaiser Permanente Redwood City</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 1 to September 25</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.018700, -122.134567,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Martinez</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25 to October 24</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.977165, -122.033150,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Concord</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25 to October 24</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.993927, -122.110367,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Kaiser Permanente Martinez</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25 to September 26</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.810085, -122.264519,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Uptown Oakland</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 24 to November 13</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.712097, -121.875381,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Dublin</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 18 to September 26</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.722332, -122.153603,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">San Leandro Downtown</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10 to October 16</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.768742, -122.390160,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Mission Bay at UCSF</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10 to December 11</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.405407, -122.140961,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">VA Palo Alto</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10 to November 13</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.768265, -122.453545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Upper Haight</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 3 to October 30</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">3:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.733608, -122.433014,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Glen Park Village</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 31 to November 24</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.932175, -121.694443,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="#interactive-map">Brentwood</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 30 to November 16</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerSeasonal(37.764557, -122.433151,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Castro</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 13 to December 18</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.532921, -121.960236,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Irvington</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.313770, -121.774284,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Evergreen</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.794563, -122.277023,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Jack London Square</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.237579, -121.800827,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Santa Teresa</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.763603, -122.465729,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Inner Sunset</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.781723, -122.503860,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">VA San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.366116, -121.828621,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Alum Rock Village</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.891785, -122.059219,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Walnut Creek</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.313770, -121.774284,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Evergreen</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.775883, -122.438354,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Divisadero</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.240883, -121.799957,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente San Jose</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(38.005455, -122.290138,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Pinole</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.782627, -122.442932,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.824219, -122.257721,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Oakland</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.431469, -121.895882,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Milpitas at ICC</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(38.017113, -122.136963,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Martinez</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.682426, -121.771545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Livermore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.820637, -122.000221,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Danville</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.977165, -122.033150,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Concord</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.518806, -122.273613,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Belmont</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.774246, -122.276756,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Alameda</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.659431, -121.875977,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Pleasanton</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.783260, -122.432907,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Fillmore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.532719, -122.337852,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">San Mateo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.763214, -122.458214,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">UCSF Parnassus</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 3:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.552238, -121.976601,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Fremont</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.607075, -122.084122,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Union City</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.630672, -122.095512,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Hayward</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(38.125957, -122.247849,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Vallejo</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.335991, -121.998695,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Kaiser Permanente Santa Clara</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">8:30 AM to 1:30 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.402180, -121.847839,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Berryessa</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(38.101154, -122.257462,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Vallejo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.329033, -122.013412,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Vallco</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.596630, -122.078751,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Union City</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
addMarkerOpen(37.774246, -122.276756,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="#interactive-map">Alameda</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="#interactive-map">Get directions...</a></p></div>');
//]]>
	center = bounds.getCenter();
 }
