// JavaScript Document
	 var openIcon = {
          url: 'images/gmap_open_icon.png',
          size: new google.maps.Size(24, 24),
          origin: new google.maps.Point(0,0),
          anchor: new google.maps.Point(5, 24)
        };
		
		var seasonalIcon = {
          url: 'images/gmap_open_icon.png',
          size: new google.maps.Size(24, 24),
          origin: new google.maps.Point(0,0),
          anchor: new google.maps.Point(-8, 36)
        };
		
		var closedIcon = {
          url: 'images/gmap_closed_icon.png',
          size: new google.maps.Size(24, 24),
          origin: new google.maps.Point(0,0),
          anchor: new google.maps.Point(21, 24)
        };

 var center = null;
 var map = null;
 var currentPopup;
 var bounds = new google.maps.LatLngBounds();
 
 function addMarkerOpen(lat, lng, html) {
	 var pt = new google.maps.LatLng(lat, lng);
	 bounds.extend(pt);
	var marker = new google.maps.Marker({
			 position: pt,
			 icon: openIcon,
			 map: map
		 });
		 
	var popup = new google.maps.InfoWindow({
		 content: html,
		 maxWidth: 150
	 });
	
	google.maps.event.addListener(marker, "click", function() {
		 if (currentPopup != null) {
			 currentPopup.close();
			 currentPopup = null;
		 }
		 popup.open(map, marker);
		 currentPopup = popup;
	});
	 google.maps.event.addListener(popup, "closeclick", function() {
	 currentPopup = null;
	 });
 }
 
 function addMarkerSeasonal(lat, lng, html) {
	 var pt = new google.maps.LatLng(lat, lng);
	 bounds.extend(pt);
	var marker = new google.maps.Marker({
			 position: pt,
			 icon: seasonalIcon,
			 map: map
		 });
	var popup = new google.maps.InfoWindow({
		 content: html,
		 maxWidth: 150
	 });
	google.maps.event.addListener(marker, "click", function() {
		 if (currentPopup != null) {
			 currentPopup.close();
			 currentPopup = null;
		 }
		 popup.open(map, marker);
		 currentPopup = popup;
	});
	 google.maps.event.addListener(popup, "closeclick", function() {
	 currentPopup = null;
	 });
 }

 function addMarkerClosed(lat, lng, html) {
	 var pt = new google.maps.LatLng(lat, lng);
	 bounds.extend(pt);
	var marker = new google.maps.Marker({
			 position: pt,
			 icon: closedIcon,
			 map: map
		 });
	 var popup = new google.maps.InfoWindow({
		 content: html,
		 maxWidth: 150
	 });
	google.maps.event.addListener(marker, "click", function() {
		 if (currentPopup != null) {
			 currentPopup.close();
			 currentPopup = null;
		 }
		 popup.open(map, marker);
		 currentPopup = popup;
	});
	 google.maps.event.addListener(popup, "closeclick", function() {
	 currentPopup = null;
	 });
 }

 function initialize() {
	 map = new google.maps.Map(document.getElementById("map_canvas"), {
		 center: new google.maps.LatLng(37.7945928242851, -121.81365966796875),
		 zoom: 8,
		 mapTypeId: google.maps.MapTypeId.ROADMAP,
		 mapTypeControl: false,
		 mapTypeControlOptions: {
			style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR
		 },
		 navigationControl: true,
		 navigationControlOptions: {
			style: google.maps.NavigationControlStyle.SMALL
		}
	});

	// extracting and looping through data
		 
 //<![CDATA[
addMarkerClosed(37.955246, -122.332397,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=86">San Pablo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SanPabloFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 18, 2013 to October 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.679829, -121.768784,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=6">Livermore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/LivermoreFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 16, 2013 to October 17, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.003571, -121.841812,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=70">Antioch at Somersville Towne Center</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/pages/Antioch-Farmers-Market-at-Somersville-Towne-Center/351959301521275" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 12, 2013 to October 27, 2013</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.332016, -121.913429,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=84">Hanchett Avenue</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/HanchettFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11, 2013 to October 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.788280, -122.420189,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=82">Fern Alley</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/pages/Fern-Alley-Farmers-Market/256975507736020" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11, 2013 to October 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.940849, -121.935921,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=28">Clayton</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/ClaytonMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 11, 2013 to October 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.926376, -122.384911,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=65">Point Richmond</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/PointRichmondFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 9, 2013 to September 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.936546, -122.356728,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=87">Richmond Main Street</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/pages/Richmond-Main-Street-Farmers-Market/226558170798206" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 8, 2013 to October 30, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.345058, -121.876915,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=85">East Santa Clara Street</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/pages/Julian-St-James-Farmers-Market/130665573736496" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 8, 2013 to October 23, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.658943, -122.439545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=26">Kaiser South San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 7, 2013 to October 15, 2013</dd><dt class="gmapInfoWindowAPIv3"> Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.543766, -122.309883,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=40">25th Avenue in San Mateo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/25thAveFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 7, 2013 to October 15, 2013</dd><dt class="gmapInfoWindowAPIv3"> Tuesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 7:30 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.634850, -122.419434,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=68">San Bruno</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SanBrunoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 5, 2013 to November 24, 2013</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.032188, -121.883759,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=34">Pittsburg</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/PittsburgFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4, 2013 to December 14, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.654930, -122.426704,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=37">South San Francisco</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SouthCityFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4, 2013 to October 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.678699, -122.126907,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=60">San Lorenzo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SanLorenzoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4, 2013 to October 19, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.944740, -122.061615,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=38">Pleasant Hill</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/PleasantHillFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4, 2013 to November 16, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.356686, -121.989304,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=51">Vacaville</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/VacavilleFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 4, 2013 to October 12, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.335411, -121.893127,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=14">San Jose Downtown</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/DowntownSanJoseFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 3, 2013 to November 22, 2013</dd><dt class="gmapInfoWindowAPIv3"> Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.951717, -121.776802,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=27">Kaiser Permanente Antioch</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 2, 2013 to October 31, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.249386, -122.041908,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=36">Fairfield</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/FairfieldMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 2, 2013 to October 3, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">3:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.488914, -122.221664,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=39">Kaiser Permanente Redwood City</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">May 1, 2013 to September 25, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(38.018700, -122.134567,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=7">Martinez</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/MartinezFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25, 2013 to October 24, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.977165, -122.033150,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=3">Concord</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/ConcordFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25, 2013 to October 24, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.993927, -122.110367,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=42">Kaiser Permanente Martinez</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 25, 2013 to September 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.810085, -122.264519,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=81">Uptown Oakland</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/OrdwayFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 24, 2013 to November 13, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.712097, -121.875381,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=45">Dublin</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/DublinMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 18, 2013 to September 26, 2013</dd><dt class="gmapInfoWindowAPIv3"> Thursday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.722332, -122.153603,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=21">San Leandro Downtown</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SanLeandroFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10, 2013 to October 16, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.768742, -122.390160,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=66">Mission Bay at UCSF</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/MissionBayFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10, 2013 to December 11, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.405407, -122.140961,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=62">VA Palo Alto</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/VAPaltoAltoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 10, 2013 to November 13, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.768265, -122.453545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=41">Upper Haight</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/UpperHaightFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">April 3, 2013 to October 30, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">3:00 PM to 7:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.733608, -122.433014,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=46">Glen Park Village</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/GlenParkVillageFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 31, 2013 to November 24, 2013</dd><dt class="gmapInfoWindowAPIv3"> Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerClosed(37.932175, -121.694443,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3 closedMarket" href="market_home.php?market_id=25">Brentwood</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/BrentwoodFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 30, 2013 to November 16, 2013</dd><dt class="gmapInfoWindowAPIv3"> Saturday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 12:00 PM</dd></dl><p class="gmapInfoWindowAPIv3 closedSeason">Closed for the season.</p></div>');
addMarkerSeasonal(37.764557, -122.433151,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=64">Castro</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/CastroFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">March 13, 2013 to December 18, 2013</dd><dt class="gmapInfoWindowAPIv3"> Wednesday</dt><dd class="gmapInfoWindowAPIv3">4:00 PM to 8:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=64&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(37.532921, -121.960236,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=61">Irvington</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/IrvingtonMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=61&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.313770, -121.774284,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=57">Evergreen</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/EvergreenFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=57&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(37.794563, -122.277023,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=5">Jack London Square</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/jlsfarmersmarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=5&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.237579, -121.800827,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=58">Santa Teresa</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/SantaTeresaFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=58&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.763603, -122.465729,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=67">Inner Sunset</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/InnerSunsetMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=67&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.781723, -122.503860,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=80">VA San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=80&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(37.366116, -121.828621,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=43">Alum Rock Village</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/AlumRockVillageFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=43&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.891785, -122.059219,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=44">Kaiser Permanente Walnut Creek</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=44&amp;market_day=2">Get directions...</a></p></div>');
addMarkerOpen(37.313770, -121.774284,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=57">Evergreen</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/EvergreenFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=57&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.775883, -122.438354,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=63">Divisadero</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/DivisaderoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=63&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.240883, -121.799957,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=22">Kaiser Permanente San Jose</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=22&amp;market_day=5">Get directions...</a></p></div>');
addMarkerOpen(38.005455, -122.290138,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=11">Pinole</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/PinoleFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=11&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.782627, -122.442932,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=10">Kaiser Permanente San Francisco</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=10&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(37.824219, -122.257721,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=9">Kaiser Permanente Oakland</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=9&amp;market_day=5">Get directions...</a></p></div>');
addMarkerOpen(37.431469, -121.895882,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=8">Milpitas at ICC</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/MilpitasFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">8:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=8&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(38.017113, -122.136963,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=7">Martinez</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/MartinezFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=7&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.682426, -121.771545,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=6">Livermore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/LivermoreFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=6&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.820637, -122.000221,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=4">Danville</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/DanvilleFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=4&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.977165, -122.033150,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=3">Concord</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/ConcordFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=3&amp;market_day=2">Get directions...</a></p></div>');
addMarkerOpen(37.518806, -122.273613,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=2">Belmont</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/BelmontMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Sunday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=2&amp;market_day=0">Get directions...</a></p></div>');
addMarkerOpen(37.774246, -122.276756,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=1">Alameda</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/AlamedaFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=1&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.659431, -121.875977,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=12">Pleasanton</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/PleasantonFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=12&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.783260, -122.432907,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=13">Fillmore</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/FillmoreFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=13&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.532719, -122.337852,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=15">San Mateo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/CollegeofSanMateoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=15&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.763214, -122.458214,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=35">UCSF Parnassus</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 3:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=35&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(37.552238, -121.976601,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=33">Kaiser Permanente Fremont</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Thursday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=33&amp;market_day=4">Get directions...</a></p></div>');
addMarkerOpen(37.607075, -122.084122,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=32">Kaiser Permanente Union City</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=32&amp;market_day=2">Get directions...</a></p></div>');
addMarkerOpen(37.630672, -122.095512,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=31">Kaiser Permanente Hayward</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Wednesday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=31&amp;market_day=3">Get directions...</a></p></div>');
addMarkerOpen(38.125957, -122.247849,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=30">Kaiser Permanente Vallejo</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">10:00 AM to 2:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=30&amp;market_day=5">Get directions...</a></p></div>');
addMarkerOpen(37.335991, -121.998695,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=29">Kaiser Permanente Santa Clara</a><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">8:30 AM to 1:30 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=29&amp;market_day=5">Get directions...</a></p></div>');
addMarkerOpen(37.402180, -121.847839,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=20">Berryessa</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/BerryessaFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=20&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(38.101154, -122.257462,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=19">Vallejo</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/VallejoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=19&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.329033, -122.013412,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=18">Vallco</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/VallcoFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Friday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=18&amp;market_day=5">Get directions...</a></p></div>');
addMarkerOpen(37.596630, -122.078751,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=17">Union City</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/pages/Union-Citys-Farmers-Market/216876678385931" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Saturday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=17&amp;market_day=6">Get directions...</a></p></div>');
addMarkerOpen(37.774246, -122.276756,'<div class="gmapInfoWindowAPIv3Container"><a class="gmapInfoWindowAPIv3 marketNameAPIv3" href="market_home.php?market_id=1">Alameda</a><p class="facebookLinkAPIv3"><a class="gmapInfoWindowAPIv3" href="http://www.facebook.com/AlamedaFarmersMarket" target="_top"><img src="images/facebook_logo_tiny.png" width="16" height="16" alt="Facebook logo" />&nbsp;Facebook Page</a></p><dl class="gmapInfoWindowAPIv3"><dt class="gmapInfoWindowAPIv3">Season</dt><dd class="gmapInfoWindowAPIv3">Year-Round</dd><dt class="gmapInfoWindowAPIv3">Tuesday</dt><dd class="gmapInfoWindowAPIv3">9:00 AM to 1:00 PM</dd></dl><p class="gmapInfoWindowAPIv3"><a class="gmapInfoWindowAPIv3" href="/market_directions.php?market_id=1&amp;market_day=2">Get directions...</a></p></div>');
//]]>
	center = bounds.getCenter();
 }